import { config } from "dotenv";
import { connectDB } from "../config/mongodb.js";
import Teacher from "../models/teacher.model.js";
import Student from "../models/student.model.js"; // Add student model if required

config();

const seedUsers = {
  students: [
    // Students
      {
        email: "juan.dela.cruz@example.com",
        firstName: "Juan",
        lastName: "Dela Cruz",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "maria.santos@example.com",
        firstName: "Maria",
        lastName: "Santos",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "andrew.bautista@example.com",
        firstName: "Andrew",
        lastName: "Bautista",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/2.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "liza.perez@example.com",
        firstName: "Liza",
        lastName: "Perez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/3.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "david.garcia@example.com",
        firstName: "David",
        lastName: "Garcia",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "susan.reyes@example.com",
        firstName: "Susan",
        lastName: "Reyes",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "pedro.diaz@example.com",
        firstName: "Pedro",
        lastName: "Diaz",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "mary.aguinaldo@example.com",
        firstName: "Mary",
        lastName: "Aguinaldo",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/5.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "ronald.santiago@example.com",
        firstName: "Ronald",
        lastName: "Santiago",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "jenna.mendoza@example.com",
        firstName: "Jenna",
        lastName: "Mendoza",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "7",
      },
      {
        email: "antonio.ramos@example.com",
        firstName: "Antonio",
        lastName: "Ramos",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "isabel.cruz@example.com",
        firstName: "Isabel",
        lastName: "Cruz",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "carlos.fernandez@example.com",
        firstName: "Carlos",
        lastName: "Fernandez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/2.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "grace.martinez@example.com",
        firstName: "Grace",
        lastName: "Martinez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/3.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "jorge.gomez@example.com",
        firstName: "Jorge",
        lastName: "Gomez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "valerie.dela.pena@example.com",
        firstName: "Valerie",
        lastName: "Dela Pena",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "rafael.moreno@example.com",
        firstName: "Rafael",
        lastName: "Moreno",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "anna.santiago@example.com",
        firstName: "Anna",
        lastName: "Santiago",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/5.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "manolo.rivera@example.com",
        firstName: "Manolo",
        lastName: "Rivera",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "julia.ponce@example.com",
        firstName: "Julia",
        lastName: "Ponce",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "8",
      },
      {
        email: "marcos.torres@example.com",
        firstName: "Marcos",
        lastName: "Torres",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/6.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "carmen.bautista@example.com",
        firstName: "Carmen",
        lastName: "Bautista",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/7.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "rafael.javier@example.com",
        firstName: "Rafael",
        lastName: "Javier",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "claudia.perez@example.com",
        firstName: "Claudia",
        lastName: "Perez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/8.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "luis.morales@example.com",
        firstName: "Luis",
        lastName: "Morales",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/8.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "amanda.reyes@example.com",
        firstName: "Amanda",
        lastName: "Reyes",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/9.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "eduardo.benitez@example.com",
        firstName: "Eduardo",
        lastName: "Benitez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "sofia.ortiz@example.com",
        firstName: "Sofia",
        lastName: "Ortiz",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/10.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "antonio.romero@example.com",
        firstName: "Antonio",
        lastName: "Romero",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "elena.silva@example.com",
        firstName: "Elena",
        lastName: "Silva",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/11.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "9",
      },
      {
        email: "alejandro.suarez@example.com",
        firstName: "Alejandro",
        lastName: "Suarez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/11.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "gabriela.villanueva@example.com",
        firstName: "Gabriela",
        lastName: "Villanueva",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "julio.castro@example.com",
        firstName: "Julio",
        lastName: "Castro",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/12.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "patricia.morales@example.com",
        firstName: "Patricia",
        lastName: "Morales",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/13.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "fernando.diaz@example.com",
        firstName: "Fernando",
        lastName: "Diaz",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/13.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "luisa.rodriguez@example.com",
        firstName: "Luisa",
        lastName: "Rodriguez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/14.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "carlos.garcia@example.com",
        firstName: "Carlos",
        lastName: "Garcia",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/14.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "maria.jimenez@example.com",
        firstName: "Maria",
        lastName: "Jimenez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/15.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "jorge.moreno@example.com",
        firstName: "Jorge",
        lastName: "Moreno",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/men/15.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      },
      {
        email: "veronica.perez@example.com",
        firstName: "Veronica",
        lastName: "Perez",
        password: "123456",
        profilePic: "https://randomuser.me/api/portraits/women/16.jpg",
        accountStatus: "Verified",
        role: "Student",
        gradeLevel: "10",
      }
    
    
    
  ],

  teachers: [
    // Teachers
    {
      email: "ajgalang@gmail.com",
      firstName: "Ara Jane",
      lastName: "Galang",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "sheenabelleca@gmail.com",
      firstName: "Sheena",
      lastName: "Belleca",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/2.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "jmpascua@gmail.com",
      firstName: "Jamica",
      lastName: "Pascua",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "rzepe@gmail.com",
      firstName: "Rachel",
      lastName: "Zape",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "mrbelano@gmail.com",
      firstName: "Mary Rose",
      lastName: "Belano",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "mfperiera@gmail.com",
      firstName: "Ma. Ferly",
      lastName: "Periera",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/6.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "mjreconcillo@gmail.com",
      firstName: "Mark Joffet",
      lastName: "Reconcillo",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "mabotial@gmail.com",
      firstName: "Michelle Ann",
      lastName: "Botial",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/8.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "ccaballero@gmail.com",
      firstName: "Catherine",
      lastName: "Caballero",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/9.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "cabugao@gmail.com",
      firstName: "Catherine",
      lastName: "Abugao",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "jsiarot@gmail.com",
      firstName: "Jennifer",
      lastName: "Siarot",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "jlgarcera@gmail.com",
      firstName: "John Leroy",
      lastName: "Garcera",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "gconmigo@gmail.com",
      firstName: "Generoso",
      lastName: "Conmigo",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "ehpacamarra@gmail.com",
      firstName: "Earl Henrick",
      lastName: "Pacamarra",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "hrpunto@gmail.com",
      firstName: "Helen",
      lastName: "Punto",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
    {
      email: "jbgutierrez@gmail.com",
      firstName: "Janely",
      lastName: "Gutierrez",
      password: "123456",
      profilePic: "https://randomuser.me/api/portraits/men/10.jpg",
      accountStatus: "Verified",
      role: "Teacher",
    },
  ],
};

const seedDatabase = async () => {
  try {
    await connectDB();

    // Clear existing data before seeding new data (Optional)
    await Student.deleteMany({});
    // You can also seed the students data if needed
    // await Student.deleteMany({});
    // await Student.insertMany(studentsWithNames);

    // Insert the teachers data with separated firstName and lastName
    await Student.insertMany(seedUsers.students);

    console.log("Database seeded successfully");
  } catch (error) {
    console.error("Error seeding database:", error);
  }
};

// Call the function
seedDatabase();
